# Generated by Django 4.2.7 on 2024-10-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="total_max_scores",
            field=models.FloatField(default=0),
        ),
    ]
