# Generated by Django 4.2.7 on 2024-11-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_customuser_total_max_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="total_english_5_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_english_6_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_japanese_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_numbers_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_phonics_score",
            field=models.FloatField(default=0.0),
        ),
    ]
