# Generated by Django 4.2.7 on 2024-12-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_customuser_total_english_5_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="total_eiken_score",
            field=models.FloatField(default=0.0),
        ),
    ]
