# Generated by Django 4.2.7 on 2024-10-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_test_lesson_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="picture_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
