# Generated by Django 4.2.7 on 2024-10-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_test_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="picture_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
