# Generated by Django 4.2.7 on 2024-10-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_test_picture_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="english_5",
        ),
        migrations.RemoveField(
            model_name="test",
            name="english_6",
        ),
        migrations.RemoveField(
            model_name="test",
            name="japanese",
        ),
        migrations.RemoveField(
            model_name="test",
            name="numbers",
        ),
        migrations.RemoveField(
            model_name="test",
            name="phonics",
        ),
        migrations.AddField(
            model_name="test",
            name="category",
            field=models.CharField(
                choices=[
                    ("japanese", "Japanese"),
                    ("english_5", "English 5"),
                    ("english_6", "English 6"),
                    ("phonics", "Phonics"),
                    ("numbers", "Numbers"),
                ],
                default="japanese",
                max_length=20,
            ),
        ),
    ]
