# Generated by Django 4.2.7 on 2024-10-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_remove_test_english_5_remove_test_english_6_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="category",
            field=models.CharField(
                choices=[
                    ("japanese", "Japanese"),
                    ("english_5", "English 5"),
                    ("english_6", "English 6"),
                    ("phonics", "Phonics"),
                    ("numbers", "Numbers"),
                ],
                default="phonics",
                max_length=20,
            ),
        ),
    ]
