# Generated by Django 4.2.7 on 2024-10-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_alter_test_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="sound2",
            field=models.BooleanField(default=False),
        ),
    ]
