# Generated by Django 4.2.7 on 2024-10-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_question_sound2"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="double_object",
            field=models.BooleanField(default=False),
        ),
    ]
