# Generated by Django 4.2.7 on 2024-10-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_question_double_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="character_voice",
            field=models.BooleanField(default=False),
        ),
    ]
