# Generated by Django 4.2.7 on 2024-11-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_question_picture2"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="lable",
            field=models.BooleanField(default=False),
        ),
    ]
