# Generated by Django 4.2.7 on 2024-11-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_question_lable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="lable",
            new_name="label",
        ),
    ]
