# Generated by Django 4.2.7 on 2024-11-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_rename_lable_question_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="description",
            field=models.BooleanField(default=False),
        ),
    ]
