# Generated by Django 4.2.7 on 2024-11-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_question_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="word2",
            field=models.BooleanField(default=False),
        ),
    ]
