# Generated by Django 4.2.7 on 2024-11-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_question_word2"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="sound3",
            field=models.BooleanField(default=False),
        ),
    ]
