# Generated by Django 4.2.7 on 2024-11-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_question_sound3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="test_content_type",
        ),
        migrations.RemoveField(
            model_name="test",
            name="test_picture",
        ),
    ]
