# Generated by Django 4.2.7 on 2024-11-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_remove_test_test_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="score_multiplier",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
