# Generated by Django 4.2.7 on 2024-11-18 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_test_score_multiplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="score_multiplier",
        ),
    ]
