# Generated by Django 4.2.7 on 2024-11-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_remove_test_score_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="score_multiplier",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
