# Generated by Django 4.2.7 on 2024-11-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_test_score_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="sound4",
            field=models.BooleanField(default=False),
        ),
    ]
