# Generated by Django 4.2.7 on 2024-11-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_test_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="sound_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
