# Generated by Django 4.2.7 on 2024-12-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_test_sound_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="Japanese_option",
            field=models.BooleanField(default=False),
        ),
    ]
