# Generated by Django 4.2.7 on 2024-12-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0044_question_japanese_option"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="Japanese_option",
            new_name="japanese_option",
        ),
    ]
