# Generated by Django 4.2.7 on 2024-12-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_classroomrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomrequest",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
