# Generated by Django 4.2.7 on 2024-12-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0047_classroomrequest_is_accepted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="school",
        ),
    ]
