# Generated by Django 4.2.7 on 2024-12-09 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_remove_teacher_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="school",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.school"
            ),
        ),
    ]
