# Generated by Django 4.2.7 on 2024-12-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_teacher_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomrequest",
            name="unchangeable",
            field=models.BooleanField(default=False),
        ),
    ]
