# Generated by Django 4.2.7 on 2024-12-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0050_classroomrequest_unchangeable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="category",
            field=models.CharField(
                choices=[
                    ("japanese", "Japanese"),
                    ("english_5", "English 5"),
                    ("english_6", "English 6"),
                    ("phonics", "Phonics"),
                    ("numbers", "Numbers"),
                    ("eiken", "Eiken"),
                ],
                default="phonics",
                max_length=20,
            ),
        ),
    ]
