# Generated by Django 4.2.7 on 2024-12-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_alter_test_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="option_list",
        ),
    ]
