# Generated by Django 4.2.7 on 2024-12-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0052_remove_option_option_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="option_list",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
