# Generated by Django 4.2.7 on 2024-12-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0053_option_option_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="number_of_questions",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
