# Generated by Django 4.2.7 on 2024-12-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0054_test_number_of_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="total_score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
